version: '3.9'
services:
  backend:
    image: node:16-buster
    volumes:
      - ./backend:/application
    env_file:
      ./backend/.env
    working_dir: /application
    command: bash -c "yarn install"
    ports:
      - 3001:3001
  frontend:
    image: node:16-buster
    volumes:
      - ./frontend:/application
    working_dir: /application
    env_file:
      ./frontend/.env
    ports:
      - 4000:4000
    command: bash -c "yarn install"
