version: '3.9'
services:
  backend:
    image: node:16-buster
    restart: always
    volumes:
      - ./backend:/application
    env_file:
      ./backend/.env
    working_dir: /application
    command: bash -c "npm run build && node ."
    ports:
      - 3001:3001
  frontend:
    image: node:16-buster
    volumes:
      - ./frontend:/application
    working_dir: /application
    env_file:
      ./frontend/.env
    ports:
      - 4000:4000
      - 5001:5000
    command: bash -c "yarn && yarn preview"

